#%RAML 1.0 Trait

headers:
  x-cms-transactionId: 
    type: string
    minLength: 36
    maxLength: 36
    required: true
    example: "GajhdgKD-32BJHblhjc2334-Bhjdkjlk332L"     
  clientId: 
    type: string
    required: true
    example: "hsdfgysdhfcdshf37er6twgsdhfjcd"
  clientSecret:
    type: string
    required: true
    example: "dsgfhaegur457r6ewsewegrfjesh"      
        